# Generated by Django 2.2.6 on 2019-10-29 04:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_official', models.IntegerField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(auto_now=True)),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(auto_now=True)),
                ('goods', models.IntegerField(default=0)),
                ('bads', models.IntegerField(default=0)),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(blank=True, to='code_essay.Article')),
            ],
        ),
    ]
