# Generated by Django 2.2.6 on 2019-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_essay', '0002_auto_20191029_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
